export const DB_HOST = 'DB_HOST';
export const DB_PORT = 'DB_PORT';
export const DB_USER = 'DB_USER';
export const DB_PASSWORD = 'DB_PASSWORD';
export const DB_DATABASE = 'DB_DATABASE';
export const SERVER_PORT = 'SERVER_PORT';


export const JWT_SECRET = 'JWT_SECRET';

export const GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID';
export const GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET';
export const GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL';

export const MONGO_URI = 'MONGO_URI';

export const WOMPI_PUBLIC_KEY = 'WOMPI_PUBLIC_KEY';
export const WOMPI_PRIVATE_KEY = 'WOMPI_PRIVATE_KEY';
export const WOMPI_EVENTS_SECRET = 'WOMPI_EVENTS_SECRET';
export const WOMPI_BASE_URL = 'WOMPI_BASE_URL';
export const WOMPI_INTEGRITY_SECRET = 'WOMPI_INTEGRITY_SECRET';

export const BACKUP_PATH = 'BACKUP_PATH';
export const BACKUP_RETENTION_DAYS = 'BACKUP_RETENTION_DAYS';